version: "3.9"

services:
  web:
    build: .
    command: uvicorn app:main:app --host="0.0.0.0" --port=8000 --proxy-headers --reload
    volumes:
      - .:/app
    ports:
      - 8008:8000
    env_file: .env
